<?php
/**
 * Created by George Antoniou.
 * Date: 7/6/14
 * Time: 7:24 PM
 * add.php
 * To change this template use File | Settings | File Templates.
 */

if(!isset($_GET['submit'])){
    $SKU=uniqid('SKU_');
    ?>
    <form class="form-horizontal" method="get" action="index.php?action=add">
        <fieldset>

            <!-- Form Name -->
            <legend>Add Product</legend>
            <input type="hidden" value="add" name="action" />
            <input type="hidden" value="<?= $SKU ?>" name="SKU" />
            <!-- Text input-->
            <div class="control-group">
                <label class="control-label" for="SKU">SKU</label>
                <div class="controls">
                    <input id="SKU" disabled name="SKU" type="text"  value= "<?= $SKU ?>" placeholder="placeholder" class="input-medium">
                    <p class="help-block">Autogenerated SKU Number</p>
                </div>
            </div>

            <!-- Text input-->
            <div class="control-group">
                <label class="control-label" for="name">Product Name</label>
                <div class="controls">
                    <input id="name" name="name" type="text" placeholder="" class="input-medium" required="">
                    <p class="help-block">Product Name</p>
                </div>
            </div>

            <!-- Textarea -->
            <div class="control-group">
                <label class="control-label" for="description">Product Description</label>
                <div class="controls">
                    <textarea id="description" name="description">default text</textarea>
                </div>
            </div>

            <!-- Text input-->
            <div class="control-group">
                <label class="control-label" for="price">Product Price</label>
                <div class="controls">
                    <input id="price" name="price" type="text" placeholder="placeholder" class="input-medium" required="">
                    <p class="help-block">Product Price</p>
                </div>
            </div>

            <!-- Select Basic -->
            <div class="control-group">
                <label class="control-label" for="stock">Stock</label>
                <div class="controls">
                    <select id="stock" name="stock" class="input-medium">
                        <option>Option one</option>
                        <option>Option two</option>
                    </select>
                </div>
            </div>

            <!-- Select Basic -->
            <div class="control-group">
                <label class="control-label" for="CATID">Category</label>
                <div class="controls">
                    <select id="CATID" name="CATID" class="input-xlarge">
                        <option value="null">None</option>
                        <?php getCats(); ?>
                    </select>
                </div>
            </div>

            <!-- File Button -->
            <div class="control-group">
                <label class="control-label" for="img">select an image</label>
                <div class="controls">
                    <input id="img" name="img" class="input-file" type="file">
                </div>
            </div>

            <!-- Button -->
            <div class="control-group">
                <label class="control-label" for="submit">Add Product</label>
                <div class="controls">
                    <button id="submit" name="submit" class="btn btn-primary">Add</button>
                </div>
            </div>

        </fieldset>
    </form>

<?php
}
else {
    var_dump($_GET);
}

function getCats(){
    $url = 'http://'.HOST.'/'.ROOT.'/Core/RestServices/Product.php/product/category/';
    $client = curl_init($url);
    curl_setopt($client, CURLOPT_RETURNTRANSFER, 1);
    $response = curl_exec($client);
    curl_close($client);
    try{
        //$response='<test>'.$response.'/<test>';
        //echo $response;
        $xml = simplexml_load_string($response);
    }catch(Exception $e) {
        //echo $e->getMessage();
    } //var_dump($xml) ;
    foreach($xml->category as $category){
        //$parents[]=(array("id"=>$category->ID, "name"=>$category->cat_name));
        echo '<option value="'.$category->ID.'">'.$category->name.'</option>';
    }
    //return $parents;
}
